### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [BiznetGIO/neo-obs#48]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.2.5. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary neo-obs -w /tmp/ext neo-obs==0.2.5
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting neo-obs==0.2.5
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/6ec/a6721dcd9b58c/neo-obs-0.2.5.tar.gz (34 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-i7tr9cqu/neo-obs/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-i7tr9cqu/neo-obs/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-i7tr9cqu/neo-obs/pip-egg-info
         cwd: /tmp/pip-wheel-i7tr9cqu/neo-obs/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-i7tr9cqu/neo-obs/setup.py", line 11, in <module>
        with open("README.md", "rb") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by HuseinA** [comment]
we have fix the problem,
you can try it in latest version (0.2.8)

**Comment by HuseinA** [comment]
Feel free to reopen if the problem persists.
